/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f3e3d1e5-59a6-4abf-bdd7-614614db37ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_05f3TMYOa",
    "aws_user_pools_web_client_id": "5csa3korc5d0nr1hls90ouinq2",
    "oauth": {}
};


export default awsmobile;
